config/routes.rb
Rails.application.routes.draw do

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: { invitations: "invitations", registrations: "registrations" }
  post "/register", to: "registrations#create"

  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root :to => "dashboard#index"
  get "/", to: "dashboard#index"

  resources :surveys do
    get "/attempts", to: "surveys#attempts", as: "attempts"
    resources :questions
    get "/pdf/checklist/:id", to: "survey/reports#checklist", as: "checklist_pdf"
    get "/pdf/score/:id", to: "survey/reports#score", as: "score_pdf"
    get "/pdf/yes_no/:id", to: "survey/reports#yes_no", as: "yes_no_pdf"
    get "/reports/checklist/:id", to: "survey/reports#checklist", as: "checklist_report"
    get "/reports/yes_no/:id", to: "survey/reports#yes_no", as: "yes_no_report"
    get "/reports/score/:id", to: "survey/reports#score", as: "score_report"
    patch "/attempts/:id/attempt", to: "attempts#submit", as: "submit_attempt"
    patch "/attempts/:id/submit", to: "submit#submit", as: "submit_report"
    get "/submit/checklist/:id", to: "submit#checklist", as: "checklist_submit"
    get "/submit/score/:id", to: "submit#score", as: "score_submit"
    get "/submit/yes_no/:id", to: "submit#yes_no", as: "yes_no_submit"
    get "delete_attempts", to: "surveys#delete_attempts", as: "delete_attempts"
  end

  get "/dashboard", to: "dashboard#index", as: "dashboard"
  get "/questions/reorder", to: "questions#reorder", as: "reorder_questions"
  get :activities, controller: :dashboard
  get "resend_invitation/:id", to: "users#resend_invitation", as: "resend_invitation_user"

  resources :users do
    get "/attempts", to: "user/attempts#index", as: "attempts"
    get "/surveys", to: "user/surveys#index", as: "surveys"
    get "/spaces", to: "user/spaces#index", as: "spaces"
    get "delete_attempts", to: "user/attempts#delete_attempts", as: "delete_attempts"
  end

  get "/surveys/:id/attempts/new", to: "attempts#new", as: "new_attempt"
  get "/surveys/:id/clone", to: "surveys#clone", as: "clone_survey"
  get "/surveys/:id/pin", to: "surveys#pin", as: "pin_survey"
  get "/surveys/:id/unpin", to: "surveys#unpin", as: "unpin_survey"
  get "/answer/:id", to: "attempts#answer", as: "answer_attempt"
  get "/score/:id", to: "attempts#score", as: "score_attempt"
  get "/check/:id", to: "attempts#check", as: "check_attempt"

  post "/change_folder/:id", to: "space/folders#change_folder", as: "change_folder"

  post "/surveys/:id/attempts/new", to: "attempts#create"
  get "/attempts", to: "attempts#index", as: "attempts"
  get "/attempts/:id", to: "attempts#show", as: "new_survey_attempt"

  scope "archive" do
    get "/surveys", to: "surveys#archived", as: "archived_surveys"
    get "/survey/:id", to: "surveys#archive_survey", as: "archive_survey"
    get "/survey/:id/restore", to: "surveys#unarchive_survey", as: "unarchive_survey"
    get "/users", to: "users#deactivated", as: "deactivated_users"
    get "/users/:id", to: "users#deactivate_user", as: "deactivate_user"
    get "/users/:id/restore", to: "users#activate_user", as: "activate_user"
  end

  get "/search/surveys", to: "search#surveys"
  get "/search/spaces-surveys-and-folders", to: "search#spaces_surveys_and_folders"
  get "/search/archived_surveys", to: "search#archived_surveys"
  get "/search/archived_users", to: "search#archived_users"
  scope "/settings" do
    get "/profile", to: "user#profile", as: "profile"
    get "/password", to: "user#password", as: "setting_password"
    patch "/password", to: "user#update_password", as: "change_password"
    patch "/profile", to: "user#update_profile", as: "update_profile"
    get "/preferences", to: "user#preferences", as: "user_preferences"
  end
  put ":id/permission", to: "user#update_permission", as: "set_permission"
  resources :spaces do
    resources :folders, module: "space" do
      collection do
        get "folders"
      end
    end
  end

  scope "/spaces" do
    get ":id/pin", to: "spaces#pin", as: "space_pin"
    get ":id/unpin", to: "spaces#unpin", as: "space_unpin"
    get ":id/archive", to: "spaces#archive", as: "space_archive"
    get ":id/unarchive", to: "spaces#unarchive", as: "space_unarchive"
  end
end

app/controllers/search_controller.rb
class SearchController < BaseController
  def surveys
    authorize :search
    like_keyword = "%#{params[:q]}%"
    if params[:folder_id].present?
      @surveys = Survey::Survey.active.where("name ILIKE ? AND folder_id = ?", like_keyword, params[:folder_id]).limit(10).order(:name)
    else
      @surveys = Survey::Survey.all.active.where(folder_id: nil).where("name ILIKE ?", like_keyword).limit(10).order(:name)
    end
    render layout: false
  end

  def spaces_surveys_and_folders
    authorize :search
    like_keyword = "%#{params[:q]}%"
    @surveys = Survey::Survey.all.active.where("name ILIKE ?", like_keyword)
      .limit(10).order(:name).limit(4)
    @spaces = Space.where("title ILIKE ?", like_keyword).limit(4)
    @folders = Folder.where("title ILIKE ?", like_keyword).limit(4)
    render layout: false
  end

  def archived_surveys
    authorize :search
    like_keyword = "%#{params[:q]}%"
    @surveys = Survey::Survey.inactive.where("name ILIKE ?", like_keyword).limit(10).order(:name)
    render layout: false
  end

  def archived_users
    authorize :search
    like_keyword = "%#{params[:q]}%"
    @users = User.inactive.where("first_name iLIKE ANY ( array[?] )", like_keyword)
      .or(User.inactive.where("last_name iLIKE ANY ( array[?] )", like_keyword))
      .or(User.inactive.where("email iLIKE ANY ( array[?] )", like_keyword))
      .order(:first_name)
    render layout: false
  end
end

app/views/search/archived_surveys.html.erb
<% @surveys.each do |result| %>
  <a href="<%= survey_path(result) %>">
    <li role="option" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900">
      <%= result.decorate.display_name %>
    </li>
  </a>
<% end %>

app/views/search/archived_users.html.erb
<% @users.each do |user| %>
  <a href="<%= user_attempts_path(user) %>">
    <li role="option" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900">
      <%= !user.first_name.blank? ?
            user.decorate.display_name : user.email %>
    </li>
  </a>
<% end %>

app/views/search/spaces_surveys_and_folders.html.erb
<div class="py-2 mb-1">
  <% if @surveys.size > 0 %>
    <div class="my-1 mt-2 ">
      <div class="pb-4">
        <div class="absolute inset-x-0 flex items-center" aria-hidden="true">
          <div class="w-full border-t border-gray-300"></div>
        </div>
        <div class="flex justify-start absolute inset-x-0  pb-2 items-center">
          <span class=" -mt-2 px-4 pr-2 text-sm italic font-bold text-gray-500 bg-white" role="option">
            Surveys
          </span>
        </div>
      </div>
      <% @surveys.each do |result| %>
        <a href="<%= survey_path(result) %>">
          <li role="option" class="block px-4 py-1 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900">
            <%= result.name.upcase_first %>
          </li>
        </a>
      <% end %>
    </div>
  <% end %>
  <div class="">
    <% if @surveys.size > 0 && @spaces.size > 0 %>
      <div class="my-1 mt-2 ">
        <div class="pb-4">
          <div class="absolute inset-x-0 flex items-center" aria-hidden="true">
            <div class="w-full border-t border-gray-300"></div>
          </div>
          <div class="flex justify-start absolute inset-x-0  pb-2 items-center">
            <span class=" -mt-2 px-4 pr-2 text-sm italic font-bold text-gray-500 bg-white" role="option">
              Spaces
            </span>
          </div>
        </div>
      <% end %>
      <% @spaces.each do |result| %>
        <a href="<%= space_folders_path(result) %>">
          <li role="option" class="block px-4 py-1 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900">
            <%= result.title.upcase_first %>
          </li>
        </a>
      <% end %>
    </div>
    <% if (@surveys.size > 0 or @spaces.size > 0) && @folders.size > 0 %>
      <div class="my-1 mt-2 ">
        <div class="pb-4">
          <div class="absolute inset-x-0 flex items-center" aria-hidden="true">
            <div class="w-full border-t border-gray-300"></div>
          </div>
          <div class="flex justify-start absolute inset-x-0 mb-2 items-center">
            <span class=" -mt-2   px-4 pr-2 text-sm italic font-bold text-gray-500 bg-white" role="option">
              Folders
            </span>
          </div>
        </div>
      </div>
    <% end %>
    <% @folders.each do |result| %>
      <a href="<%= space_folder_path(result.space, result) %>">
        <li role="option" class="block px-4 py-1 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900">
          <%= result.title.upcase_first %>
        </li>
      </a>
    <% end %>
  </div>

app/views/search/surveys.html.erb
<% @surveys.each do |survey| %>
  <a href="<%= survey_path(survey.id) %>">
    <li role="option"  id="add-skill"  class="block px-4 py-2 text-sm text-gray-900 hover:bg-gray-100 hover:text-gray-900 cursor-pointer">
      <%= survey.name %>
    </li>
  </a>
<% end %>