config/routes.rb
Rails.application.routes.draw do

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: { invitations: "invitations", registrations: "registrations" }
  post "/register", to: "registrations#create"

  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root :to => "dashboard#index"
  get "/", to: "dashboard#index"

  resources :surveys do
    get "/attempts", to: "surveys#attempts", as: "attempts"
    resources :questions
    get "/pdf/checklist/:id", to: "survey/reports#checklist", as: "checklist_pdf"
    get "/pdf/score/:id", to: "survey/reports#score", as: "score_pdf"
    get "/pdf/yes_no/:id", to: "survey/reports#yes_no", as: "yes_no_pdf"
    get "/reports/checklist/:id", to: "survey/reports#checklist", as: "checklist_report"
    get "/reports/yes_no/:id", to: "survey/reports#yes_no", as: "yes_no_report"
    get "/reports/score/:id", to: "survey/reports#score", as: "score_report"
    patch "/attempts/:id/attempt", to: "attempts#submit", as: "submit_attempt"
    patch "/attempts/:id/submit", to: "submit#submit", as: "submit_report"
    get "/submit/checklist/:id", to: "submit#checklist", as: "checklist_submit"
    get "/submit/score/:id", to: "submit#score", as: "score_submit"
    get "/submit/yes_no/:id", to: "submit#yes_no", as: "yes_no_submit"
    get "delete_attempts", to: "surveys#delete_attempts", as: "delete_attempts"
  end

  get "/dashboard", to: "dashboard#index", as: "dashboard"
  get "/questions/reorder", to: "questions#reorder", as: "reorder_questions"
  get :activities, controller: :dashboard
  get "resend_invitation/:id", to: "users#resend_invitation", as: "resend_invitation_user"

  resources :users do
    get "/attempts", to: "user/attempts#index", as: "attempts"
    get "/surveys", to: "user/surveys#index", as: "surveys"
    get "/spaces", to: "user/spaces#index", as: "spaces"
    get "delete_attempts", to: "user/attempts#delete_attempts", as: "delete_attempts"
  end

  get "/surveys/:id/attempts/new", to: "attempts#new", as: "new_attempt"
  get "/surveys/:id/clone", to: "surveys#clone", as: "clone_survey"
  get "/surveys/:id/pin", to: "surveys#pin", as: "pin_survey"
  get "/surveys/:id/unpin", to: "surveys#unpin", as: "unpin_survey"
  get "/answer/:id", to: "attempts#answer", as: "answer_attempt"
  get "/score/:id", to: "attempts#score", as: "score_attempt"
  get "/check/:id", to: "attempts#check", as: "check_attempt"

  post "/change_folder/:id", to: "space/folders#change_folder", as: "change_folder"

  post "/surveys/:id/attempts/new", to: "attempts#create"
  get "/attempts", to: "attempts#index", as: "attempts"
  get "/attempts/:id", to: "attempts#show", as: "new_survey_attempt"

  scope "archive" do
    get "/surveys", to: "surveys#archived", as: "archived_surveys"
    get "/survey/:id", to: "surveys#archive_survey", as: "archive_survey"
    get "/survey/:id/restore", to: "surveys#unarchive_survey", as: "unarchive_survey"
    get "/users", to: "users#deactivated", as: "deactivated_users"
    get "/users/:id", to: "users#deactivate_user", as: "deactivate_user"
    get "/users/:id/restore", to: "users#activate_user", as: "activate_user"
  end

  get "/search/surveys", to: "search#surveys"
  get "/search/spaces-surveys-and-folders", to: "search#spaces_surveys_and_folders"
  get "/search/archived_surveys", to: "search#archived_surveys"
  get "/search/archived_users", to: "search#archived_users"
  scope "/settings" do
    get "/profile", to: "user#profile", as: "profile"
    get "/password", to: "user#password", as: "setting_password"
    patch "/password", to: "user#update_password", as: "change_password"
    patch "/profile", to: "user#update_profile", as: "update_profile"
    get "/preferences", to: "user#preferences", as: "user_preferences"
  end
  put ":id/permission", to: "user#update_permission", as: "set_permission"
  resources :spaces do
    resources :folders, module: "space" do
      collection do
        get "folders"
      end
    end
  end

  scope "/spaces" do
    get ":id/pin", to: "spaces#pin", as: "space_pin"
    get ":id/unpin", to: "spaces#unpin", as: "space_unpin"
    get ":id/archive", to: "spaces#archive", as: "space_archive"
    get ":id/unarchive", to: "spaces#unarchive", as: "space_unarchive"
  end
end

app/views/shared/_archive_menu.html.erb
<aside class="px-2 py-6 sm:px-6 lg:py-0 lg:px-0 lg:col-span-3">
  <nav class="space-y-1">
    <a href=<%= archived_surveys_path %> class="<%= current_page?(archived_surveys_path) ? "selected" : "unselected" %>">
      <!-- Heroicon name: outline/user-circle -->
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="svg-icon">
        <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25M9 16.5v.75m3-3v3M15 12v5.25m-4.5-15H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
      </svg>
      <span class="truncate">
        Archived Surveys
      </span>
    </a>
    <a href=<%= deactivated_users_path %> class="<%= current_page?(deactivated_users_path) ? "selected" : "unselected" %>">
      <!-- Heroicon name: outline/key -->
      <svg class="svg-icon" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z" />
      </svg>
      <span class="truncate">
        Deactivated Users
      </span>
    </a>
  </nav>
</aside>

app/views/shared/_error_messages.html.erb
<% if resource&.errors&.any? %>
  <!-- This example requires Tailwind CSS v2.0+ -->
  <div class="p-4 rounded-md bg-red-50" id="error_explanation">
    <div class="flex">
      <div class="flex-shrink-0">
        <!-- Heroicon name: solid/x-circle -->
        <svg class="w-5 h-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="ml-3">
        <h3 class="text-sm font-medium text-red-800">
          <%= I18n.t("errors.messages.not_saved",
                     count: resource.errors.count,
                     resource: resource.class.model_name.human.downcase) %>
        </h3>
        <div class="mt-2 text-sm text-red-700">
          <ul class="pl-5 space-y-1 list-disc">
            <% resource.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_form_header.html.erb
<div >
  <h1 class="text-lg leading-6 font-medium text-gray-900">
    <%= title %>
  </h1>
  <p class="mt-1 text-sm text-gray-500">
    <%= subtitle %>
  </p>
</div>

app/views/shared/_form_messages.html.erb
<% if message %>
  <%= render "devise/shared/success_message", message: message %>
<% end %>
<%= render "devise/shared/error_messages", resource: resource %>

app/views/shared/_job.html.erb
<!-- Odd row -->
<tr class="bg-white border-b border-gray-200">
  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 w-full">
    <%= job.name %>
  </td>
  <% job.roles.table.keys.each do |role| %>
    <td class="px-4 py-4 whitespace-nowrap text-sm text-gray-500">
      <a href="/<%= current_user.account_id.to_s + job.roles[role] %>" class="w-20 inline-flex justify-center px-2 py-1 border border-gray-300 shadow-sm text-xs font-medium rounded text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
        <%= role.to_s.titleize %>
      </a>
    </td>
  <% end %>
</tr>

app/views/shared/_modal.html.erb
<div id="modal">
  <!-- This example requires Tailwind CSS v2.0+ -->
  <div class="fixed inset-0 z-10 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true"  data-controller="modal" data-action="keyup@document->modal#escClose">
    <div class="flex items-end justify-center min-h-screen px-4 pt-4 pb-20 text-center sm:block sm:p-0">
      <!--
      Background overlay, show/hide based on modal state.

      Entering: "ease-out duration-300"
        From: "opacity-0"
        To: "opacity-100"
      Leaving: "ease-in duration-200"
        From: "opacity-100"
        To: "opacity-0"
    -->
      <div class="fixed inset-0 transition-opacity bg-gray-500 bg-opacity-75" aria-hidden="true"></div>
      <!-- This element is to trick the browser into centering the modal contents. -->
      <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
      <!--
      Modal panel, show/hide based on modal state.

      Entering: "ease-out duration-300"
        From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        To: "opacity-100 translate-y-0 sm:scale-100"
      Leaving: "ease-in duration-200"
        From: "opacity-100 translate-y-0 sm:scale-100"
        To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
    -->
      <div class="inline-block px-4 pt-5 pb-4 overflow-hidden text-left align-bottom transition-all transform bg-white rounded-lg shadow-xl sm:my-8 sm:align-middle sm:max-w-lg sm:w-full sm:p-6">
        <div class="sm:flex sm:items-start">
          <div class="flex items-center justify-center flex-shrink-0 w-12 h-12 mx-auto bg-red-100 rounded-full sm:mx-0 sm:h-10 sm:w-10">
            <!-- Heroicon name: outline/exclamation -->
            <svg class="w-6 h-6 text-red-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
          </div>
          <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
            <h3 class="text-lg font-medium leading-6 text-gray-900" id="modal-title">
              <%= title %>
            </h3>
            <div class="mt-2">
              <p class="text-sm text-gray-500">
                <%= message %>
              </p>
            </div>
          </div>
        </div>
        <div class="mt-5 sm:mt-4 sm:flex sm:flex-row-reverse">
          <% if main_button_visible %>
            <button type="button" class="inline-flex justify-center w-full px-4 py-2 text-base font-medium text-white bg-red-600 border border-transparent rounded-md shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:ml-3 sm:w-auto sm:text-sm">
              Deactivate
            </button>
          <% end %>
          <button type="button" class="inline-flex justify-center w-full px-4 py-2 mt-3 text-base font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:w-auto sm:text-sm" data-action="modal#close">
            Cancel
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<script>
  window.dropdowns = function() {
      return {
          show: false, // controls tabs menu dropdown
          open: false, //controls profile menu dropdown
          displayMobileDropdown() { return  this.show ? "block" : "hidden"},
          hideMobileDropdown() { return  this.show ? "hidden" : "block" },
          toggle() {this.show = !this.show} //toggles mobile dropdown menu
      }
  }
</script>
<nav class="bg-gray-800 navbar">
  <div class="px-2 mx-auto sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-12">
      <div class="flex items-center justify-center flex-1 sm:items-stretch sm:justify-start">
        <div class="flex items-center flex-shrink-0">
          <a class="flex" href="<%= dashboard_path %>">
            <div class="flex items-center flex-shrink-0">
              <h1 class="text-white font-extrabold font-mono">Quick Survey</h1>
            </div>
          </a>
        </div>
        <% if user_signed_in? %>
          <div class="hidden sm:block sm:ml-2 pl-4">
            <div class="flex space-x-2">
              <a href=<%= dashboard_path %> class= "<%= current_page?(dashboard_path) ? "nav-selected" : "nav-unselected" %>">Dashboard</a>
              <% if policy(:spaces).index? %>
                <a href=<%= spaces_path %> class= "<%= current_page?(spaces_path) ? "nav-selected" : "nav-unselected" %>">Spaces</a>
              <% end %>
              <% if policy(:survey).index? %>
                <a href=<%= surveys_path %> class= "<%= current_page?(surveys_path) ? "nav-selected" : "nav-unselected" %>"> Surveys </a>
              <% end %>
              <a href="<%= attempts_path %> " class="<%= current_page?(attempts_path) ? "nav-selected" : "nav-unselected" %>">Attempts</a>
              <% if policy(:Users).index? %>
                <a href=<%= users_path %> class= "<%= current_page?(users_path) ? "nav-selected" : "nav-unselected" %>"> Users </a>
              <% end %>
            </div>
          </div>
        </div>
        <% if !current_user.member? %>
          <div class="flex  w-5/12 px-2 lg:ml-6 lg:justify-end"  data-behavior="autocomplete" data-controller="nav-search" data-nav-search-url-value="<%= current_user.account_id %>/search/spaces-surveys-and-folders">
            <div class="w-full max-w-xs lg:max-w-sm justify-end">
              <div class="relative">
                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none" >
                  <!-- Heroicon name: solid/search -->
                  <svg class="w-5 h-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
                  </svg>
                </div>
                <input id="search" name="search" class="block w-full py-1 pl-10 pr-3 leading-5 text-gray-300 placeholder-gray-400 bg-gray-700 border border-transparent rounded-md focus:outline-none focus:bg-white focus:border-white focus:ring-white focus:text-gray-900 sm:text-sm" placeholder="Search Surveys or Spaces or Folders" type="search" data-nav-search-target="input">
              </div>
              <div class="relative">
                <div class="absolute  left-0 z-20 block w-full mt-2 origin-top-right bg-white rounded-md shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
                  <ul data-nav-search-target="results" id="results">
                  </ul>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <div data-controller="dropdown">
          <!-- This example requires Tailwind CSS v2.0+ -->
          <nav class="bg-gray-800" id="menubar">
            <div class="absolute inset-y-0 right-0 items-center flex-shrink-0 pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
              <!-- Profile dropdown -->
              <div  class="relative z-10 ml-3">
                <div>
                  <button data-action="click->dropdown#toggle click@window->dropdown#hide" class="flex text-sm bg-gray-800 rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white" id="user-menu" aria-haspopup="true">
                    <%= image_tag "male-placeholder-image.png", class: "w-8 h-8 rounded-full" %>
                  </button>
                </div>
                <div  class="absolute right-0 w-48 mt-2 origin-top-right rounded-md shadow-lg">
                  <div class="hidden absolute right-0 py-1 mt-2 origin-top-right bg-white rounded-md shadow-lg w-60 ring-1 ring-black ring-opacity-5" role="menu" aria-orientation="vertical" aria-labelledby="user-menu" data-dropdown-target="menu">
                    <div class= "px-4 py-3">
                      <p class="text-sm">Signed in as</p>
                      <p class="text-xs text-gray-400 truncate font-small max-w-auto"><%= current_user.email %></p>
                    </div>
                    <div class="border-t border-gray-100">
                      <div>
                        <a><%= link_to "Settings", profile_path, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem" %></a>
                        <% if policy(:users).deactivated? %>
                          <a><%= link_to "Archive", archived_surveys_path, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem" %></a>
                        <% end %>
                        <a><%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem" %></a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% else %>
            <div class="hidden md:flex items-center justify-end md:flex-1 lg:w-0">
              <a href=<%= new_user_registration_path %> class="<%= current_page?(new_user_registration_path) ? "nav-selected" : "nav-unselected" %>">Sign up </a>
              <a href=<%= new_user_session_path %> class="<%= current_page?(new_user_session_path) ? "nav-selected" : "nav-unselected" %>"  >Sign in</a>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </nav>

app/views/shared/_paginator.html.erb
<% link = pagy_anchor(pagy) -%>
<nav aria-label="pager" class="inline-flex border border-gray-200 rounded-sm shadow-md pagy_nav pagination" role="navigation">
  <% if pagy.prev -%>  <span class="px-3 py-2 text-sm font-medium leading-tight text-gray-700 border-r border-gray-200 page prev hover:text-gray-900 hover:bg-gray-100"><%== link.(pagy.prev, "&lt;", aria_label: "Previous") %></span>
  <% else -%>  <span class="px-3 py-2 text-sm font-medium leading-tight text-gray-700 border-r border-gray-200 cursor-not-allowed page prev hover:bg-gray-100 disabled">    <a role="link" aria-disabled="true" aria-label="Previous">&lt;</a>
    </span>
  <% end -%>
  <% pagy.series.each do |item| -%>
    <% if item.is_a?(Integer) -%>  <span class="px-3 py-2 text-sm font-medium leading-tight text-gray-700 border-r border-gray-200 page hover:text-gray-900 hover:bg-gray-100"><%== link.(item) %></span>
    <% elsif item.is_a?(String) -%>  <span class="px-3 py-2 text-sm font-medium leading-tight text-gray-700 text-blue-600 bg-gray-100 border-r border-gray-200 page current hover:text-gray-900 hover:bg-gray-100"><%= item %></span>
    <% elsif item == :gap -%>  <span class="px-3 py-2 text-sm font-medium leading-tight text-gray-700 border-r border-gray-200 page gap hover:bg-gray-100"><%== "&hellip;" %></span>
    <% end -%>
  <% end -%>
  <% if pagy.next -%>  <span class="px-3 py-2 text-sm font-medium leading-tight text-gray-700 text-gray-900 border-r border-transparent border-gray-200 page hover:text-gray-900 next hover:bg-gray-100">    <a href="<%== pagy_url_for(pagy, pagy.next) %>" rel="next" aria-disabled="true" aria-label="Next">&gt;</a>
    </span>
  <% else -%>  <span class="px-3 py-2 text-sm font-medium leading-tight text-gray-700 border-r border-gray-200 cursor-not-allowed page next disabled hover:bg-gray-100"><a role="link" aria-disabled="true" aria-label="Next">&gt;</a></span>
  <% end -%>
</nav>

app/views/shared/_settings_menu.html.erb
<aside class="px-2 py-6 sm:px-6 lg:py-0 lg:px-0 lg:col-span-3">
  <nav class="space-y-1">
    <a href=<%= profile_path %> class="<%= current_page?(profile_path) ? "selected" : "unselected" %>">
      <!-- Heroicon name: outline/user-circle -->
      <svg class="svg-icon h-6 inline-flex" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      <span class="truncate">
        Profile
      </span>
    </a>
    <a href=<%= setting_password_path %> class="<%= current_page?(setting_password_path) ? "selected" : "unselected" %>">
      <!-- Heroicon name: outline/key -->
      <svg class="svg-icon h-6 inline-flex" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z" />
      </svg>
      <span class="truncate">
        Password
      </span>
    </a>
  </nav>
</aside>

app/views/shared/_success_message.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<% if message %>
  <div class="p-4 rounded-md bg-green-50" data-controller="hide-element">
    <div class="flex">
      <div class="flex-shrink-0">
        <!-- Heroicon name: solid/check-circle -->
        <svg class="w-5 h-5 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="ml-3">
        <p class="text-sm font-medium text-green-800">
          <%= message %>
        </p>
      </div>
      <div class="hidden pl-3 ml-auto">
        <div class="-mx-1.5 -my-1.5">
          <button class="inline-flex bg-green-50 rounded-md p-1.5 text-green-500 hover:bg-green-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-green-50 focus:ring-green-600">
            <span class="sr-only">Dismiss</span>
            <!-- Heroicon name: solid/x -->
            <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_table.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="w-full px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Name
              </th>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider align-center">
              </th>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
              </th>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
              </th>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
              </th>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
              </th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: "shared/job", collection: data, as: :job %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>