config/routes.rb
Rails.application.routes.draw do

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: { invitations: "invitations", registrations: "registrations" }
  post "/register", to: "registrations#create"

  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root :to => "dashboard#index"
  get "/", to: "dashboard#index"

  resources :surveys do
    get "/attempts", to: "surveys#attempts", as: "attempts"
    resources :questions
    get "/pdf/checklist/:id", to: "survey/reports#checklist", as: "checklist_pdf"
    get "/pdf/score/:id", to: "survey/reports#score", as: "score_pdf"
    get "/pdf/yes_no/:id", to: "survey/reports#yes_no", as: "yes_no_pdf"
    get "/reports/checklist/:id", to: "survey/reports#checklist", as: "checklist_report"
    get "/reports/yes_no/:id", to: "survey/reports#yes_no", as: "yes_no_report"
    get "/reports/score/:id", to: "survey/reports#score", as: "score_report"
    patch "/attempts/:id/attempt", to: "attempts#submit", as: "submit_attempt"
    patch "/attempts/:id/submit", to: "submit#submit", as: "submit_report"
    get "/submit/checklist/:id", to: "submit#checklist", as: "checklist_submit"
    get "/submit/score/:id", to: "submit#score", as: "score_submit"
    get "/submit/yes_no/:id", to: "submit#yes_no", as: "yes_no_submit"
    get "delete_attempts", to: "surveys#delete_attempts", as: "delete_attempts"
  end

  get "/dashboard", to: "dashboard#index", as: "dashboard"
  get "/questions/reorder", to: "questions#reorder", as: "reorder_questions"
  get :activities, controller: :dashboard
  get "resend_invitation/:id", to: "users#resend_invitation", as: "resend_invitation_user"

  resources :users do
    get "/attempts", to: "user/attempts#index", as: "attempts"
    get "/surveys", to: "user/surveys#index", as: "surveys"
    get "/spaces", to: "user/spaces#index", as: "spaces"
    get "delete_attempts", to: "user/attempts#delete_attempts", as: "delete_attempts"
  end

  get "/surveys/:id/attempts/new", to: "attempts#new", as: "new_attempt"
  get "/surveys/:id/clone", to: "surveys#clone", as: "clone_survey"
  get "/surveys/:id/pin", to: "surveys#pin", as: "pin_survey"
  get "/surveys/:id/unpin", to: "surveys#unpin", as: "unpin_survey"
  get "/answer/:id", to: "attempts#answer", as: "answer_attempt"
  get "/score/:id", to: "attempts#score", as: "score_attempt"
  get "/check/:id", to: "attempts#check", as: "check_attempt"

  post "/change_folder/:id", to: "space/folders#change_folder", as: "change_folder"

  post "/surveys/:id/attempts/new", to: "attempts#create"
  get "/attempts", to: "attempts#index", as: "attempts"
  get "/attempts/:id", to: "attempts#show", as: "new_survey_attempt"

  scope "archive" do
    get "/surveys", to: "surveys#archived", as: "archived_surveys"
    get "/survey/:id", to: "surveys#archive_survey", as: "archive_survey"
    get "/survey/:id/restore", to: "surveys#unarchive_survey", as: "unarchive_survey"
    get "/users", to: "users#deactivated", as: "deactivated_users"
    get "/users/:id", to: "users#deactivate_user", as: "deactivate_user"
    get "/users/:id/restore", to: "users#activate_user", as: "activate_user"
  end

  get "/search/surveys", to: "search#surveys"
  get "/search/spaces-surveys-and-folders", to: "search#spaces_surveys_and_folders"
  get "/search/archived_surveys", to: "search#archived_surveys"
  get "/search/archived_users", to: "search#archived_users"
  scope "/settings" do
    get "/profile", to: "user#profile", as: "profile"
    get "/password", to: "user#password", as: "setting_password"
    patch "/password", to: "user#update_password", as: "change_password"
    patch "/profile", to: "user#update_profile", as: "update_profile"
    get "/preferences", to: "user#preferences", as: "user_preferences"
  end
  put ":id/permission", to: "user#update_permission", as: "set_permission"
  resources :spaces do
    resources :folders, module: "space" do
      collection do
        get "folders"
      end
    end
  end

  scope "/spaces" do
    get ":id/pin", to: "spaces#pin", as: "space_pin"
    get ":id/unpin", to: "spaces#unpin", as: "space_unpin"
    get ":id/archive", to: "spaces#archive", as: "space_archive"
    get ":id/unarchive", to: "spaces#unarchive", as: "space_unarchive"
  end
end

app/models/survey/answer.rb
class Survey::Answer < ActiveRecord::Base
  self.table_name = "survey_answers"

  #acceptable_attributes :attempt, :option, :correct, :option_id, :question, :question_id

  # associations
  belongs_to :attempt
  belongs_to :option
  belongs_to :question

  # validations
  validates :option_id, :question_id, :presence => true
  validates :option_id, :uniqueness => { :scope => [:attempt_id, :question_id] }

  # callbacks
  after_create :characterize_answer

  def value
    points = (self.option.nil? ? Survey::Option.find(option_id) : self.option).weight
    correct? ? points : -points
  end

  def correct?
    self.correct ||= self.option.correct?
  end

  private

  def characterize_answer
    update_attribute(:correct, option.correct?)
  end
end

app/models/survey/attempt.rb
class Survey::Attempt < ActiveRecord::Base
  acts_as_tenant :account
  self.table_name = "survey_attempts"

  #   acceptable_attributes :winner, :survey, :survey_id,
  #     :participant,
  #     :participant_id,
  #     :answers_attributes => ::Survey::Answer::AccessibleAttributes

  # relations
  belongs_to :survey
  belongs_to :participant
  belongs_to :actor, class_name: "User", foreign_key: "actor_id"
  has_many :answers, :dependent => :destroy
  accepts_nested_attributes_for :answers,
    :reject_if => ->(q) { q[:question_id].blank? || q[:option_id].blank? }

  # validations
  validate :check_number_of_attempts_by_survey

  #scopes
  scope :wins, -> { where(:winner => true) }
  scope :looses, -> { where(:winner => false) }
  scope :scores, -> { order("score DESC") }
  scope :for_survey, ->(survey) { where(:survey_id => survey.id) }
  scope :exclude_survey, ->(survey) { where("NOT survey_id = #{survey.id}") }
  scope :for_participant, ->(participant) {
          where(:participant_id => participant.try(:id))
        }

  # callbacks
  before_create :collect_scores

  def correct_answers
    return self.answers.where(:correct => true)
  end

  def incorrect_answers
    return self.answers.where(:correct => false)
  end

  def self.high_score
    return scores.first.score
  end

  private

  def check_number_of_attempts_by_survey
    attempts = self.class.for_survey(survey).for_participant(participant)
    upper_bound = self.survey.attempts_number

    if attempts.size >= upper_bound && upper_bound != 0
      errors.add(:survey_id, "Number of attempts exceeded")
    end
  end

  def collect_scores
    self.score = self.answers.map(&:value).reduce(:+) || 0
  end
end

app/models/survey/option.rb
class Survey::Option < ActiveRecord::Base
  self.table_name = "survey_options"

  #acceptable_attributes :text, :correct, :weight

  #relations
  belongs_to :question

  # validations
  validates :text, :presence => true, :allow_blank => false

  # scopes
  scope :correct, -> { where(:correct => true) }
  scope :incorrect, -> { where(:correct => false) }

  # callbacks
  before_create :default_option_weight

  def to_s
    return self.text
  end

  def correct?
    return (self.correct == true)
  end

  private

  def default_option_weight
    self.weight = 1 if correct? && self.weight == 0
  end
end

app/models/survey/participant.rb
class Survey::Participant < ActiveRecord::Base
  self.table_name = "survey_participant"
end

app/controllers/survey/base_controller.rb
class Survey::BaseController < BaseController
  include Pagy::Backend

  before_action :set_survey, only: [:create, :destroy, :update, :edit, :new]

  def set_survey
    @survey = Survey::Survey.find(params[:survey_id])
  end
end

app/controllers/survey/questions_controller.rb
class Survey::QuestionsController < Survey::BaseController
  before_action :set_question, only: [:edit, :update, :destroy, :show]

  def edit
    authorize [:survey, @question]
  end

  def destroy
    authorize [:survey, @question]
    @question.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@question) }
    end
  end

  def update
    authorize [:survey, @question]
    @question.update(question_params)
    redirect_to survey_path(@survey), notice: "Question was updated"
  end

  def reorder
    authorize [:survey, :question]
    @question = Survey::Question.find(params[:question_id])
    @survey = Survey::Survey.find(params[:survey_id])
    @question.update(order: params[:order].to_i)

    if @question.save
      @change_order = @survey.questions.where.not(id: @question.id).order(:order)
      @change_order.size > 0 ?
        @change_order.each do |question|
        question.order < params[:order].to_i && question.order > 0 ? question.update(order: question.order - 1) :
          question.update(order: question.order + 1)
      end : nil

      partial = render_to_string(partial: "surveys/questions/question", locals: { questions: @survey.questions.order(:order), survey: @survey })
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.update(:survey_questions, partial)
        end
        format.html
      end
    end
  end

  def create
    authorize [:survey, :question]
    @question = Survey::Question.new(question_params)
    @question.survey = @survey
    @question.order = @survey.questions.size + 1
    @question.save

    add_options(@question, @survey)

    respond_to do |format|
      if @question.persisted?
        format.turbo_stream {
          render turbo_stream: turbo_stream.update(:questions, partial: "surveys/questions/question", locals: { questions: @survey.questions.order(:order), survey: @survey }, formats: [:turbo_stream]) +
                               turbo_stream.replace(Survey::Question.new, partial: "surveys/questions/form", locals: { survey: @survey, question: Survey::Question.new, message: "Question was added successfully." })
        }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(Survey::Question.new, partial: "surveys/questions/form", locals: { survey: @survey, question: @question }) }
      end
    end
  end

  private

  def add_options(question, survey)
    if survey.survey_type == 0 #checklist
      Survey::Option.new(text: "Yes", question: question, correct: true, weight: 1).save
      Survey::Option.new(text: "No", question: question, correct: false, weight: 0).save
    else
      Survey::Option.new(text: "Score", question: question, correct: true, weight: 10).save
    end
  end

  def set_question
    @question = Survey::Question.find(params[:id])
  end

  def question_params
    params.require(:survey_question).permit(:text, :description, :survey_id)
  end
end

app/controllers/survey/reports_controller.rb
class Survey::ReportsController < Survey::BaseController
  before_action :set_attempt, only: [:checklist, :score, :submit, :yes_no]

  def checklist
    authorize [:survey, :report]
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "#{@attempt.participant.name}_#{@attempt.survey.name}",
               template: "pdf/checklist",
               layout: "pdf",
               formats: [:html]
      end
    end
  end

  def score
    authorize [:survey, :report]
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "#{@attempt.participant.name}_#{@attempt.survey.name}",
               template: "pdf/score",
               layout: "pdf",
               formats: [:html]
      end
    end
  end

  def yes_no
    authorize [:survey, :report]
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "#{@attempt.participant.name}_#{@attempt.survey.name}",
               template: "pdf/yes_no",
               layout: "pdf",
               formats: [:html]
      end
    end
  end

  private

  def attempt_params
    params.permit(:id, :comment)
  end

  def set_attempt
    @attempt ||= Survey::Attempt.find(params[:id])
  end
end

app/controllers/surveys_controller.rb
class SurveysController < BaseController
  include Pagy::Backend

  before_action :set_survey, only: [:edit, :update, :destroy, :show, :clone, :archive_survey, :unarchive_survey, :pin, :unpin]
  before_action :find_survey, only: [:attempts, :delete_attempts]

  def index
    authorize :Survey
    @title = "Home"
    surveys = Survey::Survey.all.active.where(folder_id: nil)
    @pagy, @surveys = pagy_nil_safe(params, surveys, items: LIMIT)
    render_partial("surveys/survey", collection: @surveys, cached: false) if stale?(@surveys)
  end

  def new
    authorize :Survey

    @survey = Survey::Survey.new
  end

  def edit
    authorize @survey
  end

  def destroy
    authorize @survey

    if DestroySurvey.call(@survey).result
      redirect_to archived_surveys_path, notice: "Survey was successfully deleted."
    end
  end

  def update
    authorize @survey
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to survey_path(@survey), notice: "Survey was successfully updated." }
      else
        format.html { redirect_to edit_survey_path(@survey), notice: "Failed to update survey." }
      end
    end
  end

  def create
    authorize :Survey
    @survey = Survey::Survey.new(survey_params)
    @survey.user = current_user

    respond_to do |format|
      if @survey.save
        if @survey.folder_id.present?
          @folder = Folder.find(@survey.folder_id)
          format.html { redirect_to space_folder_path(@folder.space, @folder), notice: "Survey was successfully created." }
        else
          format.html { redirect_to survey_path(@survey), notice: "Survey was successfully created." }
        end
      else
        format.html { redirect_to new_survey_path, notice: "Failed to create survey." }
      end
    end
  end

  def show
    authorize @survey
    @question = Survey::Question.new
    if RecentSurvey.where(user: current_user, survey_surveys: @survey).exists?
      RecentSurvey.where(user: current_user, survey_surveys: @survey).first.increment!(:count)
    else
      RecentSurvey.create(user: current_user, survey_surveys: @survey, count: 1)
    end
  end

  def attempts
    authorize @survey
    @survey = Survey::Survey.find(params[:survey_id])
    attempts = Survey::Attempt.where(survey_id: params[:survey_id]).includes(:participant, :survey, :actor).order(updated_at: :desc).order(created_at: :desc).all
    @pagy, @attempts = pagy(attempts, items: 10)
    render_partial("surveys/attempt", collection: @attempts, cached: true) if stale?(@attempts)
  end

  def delete_attempts
    authorize @survey
    Survey::Attempt.where(survey_id: params[:survey_id]).delete_all
    redirect_to survey_path(@survey), notice: "Survey attempts has been deleted successfully"
  end

  def pin
    authorize @survey
    @survey.update(pin: true)
    redirect_to survey_path(@survey), notice: "Survey has been pinned."
  end

  def unpin
    authorize @survey
    @survey.update(pin: false)
    redirect_to survey_path(@survey), notice: "Survey has been unpinned."
  end

  def clone
    authorize @survey

    @clone = Survey::Survey.new
    @clone.name = @survey.name + " (Copy)"
    @clone.survey_type = @survey.survey_type
    @clone.description = @survey.description.nil? ? "N/A" : @survey.description
    @clone.save

    @survey.questions.each do |question|
      cloned_question = Survey::Question.new(text: question.text, description: question.description, survey_id: @clone.id)
      cloned_question.save
      if cloned_question.persisted?
        add_options(cloned_question, @clone)
      end
    end

    redirect_to survey_path(@clone)
  end

  def archived
    authorize :survey

    surveys = Survey::Survey.inactive.order(archived_on: :asc)
    @pagy, @surveys = pagy_nil_safe(params, surveys, items: LIMIT)

    render_partial_as("surveys/archived_survey", collection: @surveys, as: :survey, cached: true) if stale?(@surveys)
  end

  def archive_survey
    authorize @survey
    if ArchiveSurvey.call(@survey).result
      redirect_to archived_surveys_path, notice: "Survey has been archived."
    end
  end

  def unarchive_survey
    authorize @survey
    @survey.update(active: true, archived_on: nil)
    redirect_to survey_path(@survey), notice: "Survey has been restored."
  end

  private

  def find_survey
    @survey = Survey::Survey.find(params[:survey_id])
  end

  def set_survey
    @survey = Survey::Survey.find(params[:id])
  end

  def survey_params
    params.require(:survey_survey).permit(:name, :survey_type, :description, :folder_id)
  end
end

app/controllers/user/surveys_controller.rb
class User::SurveysController < User::BaseController
  def index
    authorize [@user, :survey]
    surveys = Survey::Survey.active.where(user_id: @user.id).order(created_at: :desc)
    @pagy, @surveys = pagy_nil_safe(params, surveys, items: LIMIT)
    render_partial("user/surveys/survey", collection: @surveys) if stale?(@surveys)
  end
end

app/views/surveys/_archived_survey.html.erb
<tr id="<%= dom_id(survey) %>">
  <td class="w-full table-cell">
    <div class="flex items-center">
      <div class="flex-1 min-w-0 sm:flex sm:items-center sm:justify-between">
        <div>
          <a href="<%= survey_path(survey) %>" class="hover:text-gray-600 hover:underline">
            <div class="flex text-sm font-medium text-gray-600 ">
              <p> <%= survey.name %> </p>
            </div>
          </a>
          <div class="flex-1 w-full mt-2">
            <div class="flex items-center text-sm text-gray-500">
              <!-- Heroicon name: solid/calendar -->
              <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd" />
              </svg>
              <p>
                <%= survey.archived_on.nil? ? "Archive Date not added" : "Archived on " + display_date(survey.archived_on) %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </td>
    <td class="table-cell whitespace-nowrap">
      <div class="flex justify-end">
        <%= confirm_button(unarchive_survey_path(survey), "Unarchive", "Are you sure you want to activate this survey?", "btn-inline-edit mr-2") %>
        <%= delete_button(survey_path(survey)) %>
      </div>
    </div>
  </td>
</tr>

app/views/surveys/_attempt.html.erb
<% survey = attempt.survey %>
<% user = attempt.actor.decorate %>
<% participant = attempt.participant %>
<tr class="bg-white " id="<%= dom_id(attempt) %>">
  <td class=" whitespace-nowrap  table-cell">
    <a href="reports/<%= attempt.survey.survey_type %>/<%= attempt.id %>" class="hover:underline">
        <p> See Survey Result</p>

    </a>
  </td>
    <td class=" whitespace-nowrap  table-cell">
        <a href="<%= user_attempts_path(user) %>" class="hover:underline text-indigo-600 hover:text-indigo-900">

      <p> <% if user %><%= user.decorate.display_name %><% end %></p>
      </a>
  </td>

  <td class=" whitespace-nowrap  table-cell">
    <p> <%= participant.name.upcase_first %></p>
  </td>
  <td class=" whitespace-nowrap  table-cell">
    <p> <%= participant.email %></p>
  </td>
  <td class=" whitespace-nowrap  table-cell">
    <p> <%= attempt.created_at.to_date.to_formatted_s(:long) %></p>
  </td>
  <td class="table-cell whitespace-nowrap space-x-6">
    <a target="_blank" href="pdf/<%= survey.survey_type %>/<%= attempt.id %>.pdf"  class="inline-flex justify-center px-2 py-1 border border-gray-300 shadow-sm text-xs font-medium rounded text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
      Download PDF
    </a>
  </td>
</tr>

app/views/surveys/_folder_form_modal.html.erb
<div class="hidden fixed z-10 inset-0 bg-black bg-opacity-80 overflow-y-auto flex items-center justify-center"
        data-slideover-target="background"
        data-action="click->modal#closeBackground">
  <div data-slideover-target="container" class="hidden fixed inset-0 overflow-y-auto flex items-center justify-center" 
data-action="click->slideover#closeBackground"style="z-index: 9999;">
    <div class="max-w-lg max-h-screen w-full  bg-white transition-all transform shadow-xl rounded-lg relative ">
      <div class="m-1 bg-white rounded  ">
        <form id="change_folder_form"  action="/<%= survey.account_id %>/change_folder/<%= survey.id %>">
          <%= render partial: "folder_form" %>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/surveys/_survey.html.erb
<tr class="bg-white" id="<%= dom_id(survey) %>">
  <td class="flex whitespace-nowrap text-sm font-medium text-gray-900">
    <a href="<%= survey_path(survey.id) %>" class="bg-white py-2 px-4 text-sm font-medium text-gray-700 hover:underline focus:outline-none">
      <%= survey.name %>
    </a>
  </td>
  <td class="px-6 whitespace-nowrap text-right text-sm font-medium">
    <%= link_to "Edit", edit_survey_path(survey), class: "text-indigo-600 hover:text-indigo-900" %>
    <%= link_to "Show", survey_path(survey), class: "ml-4 text-indigo-600 hover:text-indigo-900" %>
    <%= confirm_button(archive_survey_path(survey), "Archive", "Are you sure you want to archive this survey?", "text-indigo-600 hover:text-indigo-900 ml-4") %>
  </td>
</tr>

app/views/surveys/_tabs.html.erb
<div id="survey-tabs">
  <div class="hidden sm:block">
    <div class="border-b border-gray-200">
      <nav class="flex -mb-px space-x-8 lg:px-6" aria-label="Tabs">
        <a href="<%= survey_path(survey) %>" class="<%= current_page?(survey_path(survey)) ? "selected-tab" : "unselected-tab" %>">
          Questions
        </a>
        <a href="<%= survey_attempts_path(survey) %>" class="<%= current_page?(survey_attempts_path(survey)) ? "selected-tab" : "unselected-tab" %>">
          Attempts
        </a>
      </nav>
    </div>
  </div>
</div>

app/views/surveys/_title.html.erb
<div class="flex-wrap items-baseline" >
  <h1 class="text-2xl px-4 py-4  font-bold leading-tight text-gray-900">
    <%= @survey.name %>
  </h1>
  <p class="px-4 text-sm -mt-2 text-gray-500 truncate"><%= @survey.description %></p>
</div>
<div class="" aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <%= render "folder_form_modal", survey: @survey %>
</div>
<div class="flex sm:mt-0 sm:ml-4 " >
  <div class="flex space-x-6">
    <% if policy(@survey).attempt? %>
      <%= link_to "Attempt", new_attempt_path(@survey), class: "py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 cursor-pointer" %>
    <% end %>
    <div   class="flex items-center justify-between ">
      <!-- This example requires Tailwind CSS v2.0+ -->
      <div class="relative z-0 inline-flex rounded-md shadow-sm" >
        <div class="relative block -ml-px" data-controller="dropdown">
          <button data-action="click->dropdown#toggle click@window->dropdown#hide"  type="button"  value="Submit" class="inline-flex py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 cursor-pointer" id="option-menu-button" >
            <span>Actions</span>
            <!-- Heroicon name: solid/chevron-down -->
            <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
          </button>
          <div  data-turbo-prefetch="false" data-dropdown-target="menu" class="hidden absolute right-0 z-10 w-56 mt-2 -mr-1 origin-top-right bg-white rounded-md shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="option-menu-button" tabindex="-1">
            <div class="py-1" role="none" id="option-menu">
              <div class="" aria-labelledby="modal-title" role="dialog" aria-modal="true">
                <%= render "folder_form_modal", survey: @survey %>
              </div>
              <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
              <% if current_user.admin? or current_user.superadmin? %>
                <li  data-action= "click->slideover#open click->dropdown#toggle", data-turbo-frame= "change_folder_modal"  class=" cursor-pointer bg-white block w-full px-4 py-2 text-sm text-left text-gray-700 hover:bg-gray-50 inline-flex" data-survey-id="<%= survey.id %>" data-account-id="<%= survey.account_id %>">
                  <p class="inline-flex" id="change-folder"><span>
                      Move To Folder</span></p>
                </li>
              <% end %>
              <% if policy(@survey).unpin? %>
                <%= link_to "Unpin Survey", unpin_survey_path(survey), class: " cursor-pointer bg-white block w-full px-4 py-2 text-sm text-left text-gray-700 hover:bg-gray-50" %>
              <% end %>
              <% if policy(@survey).pin? %>
                <%= link_to "Pin Survey", pin_survey_path(survey), class: " cursor-pointer bg-white block w-full px-4 py-2 text-sm text-left text-gray-700 hover:bg-gray-50" %>
              <% end %>
              <% if policy(@survey).clone? %>
                <%= confirm_button(clone_survey_path(@survey), "Clone", "Are you sure? This will create a new survey by copying everything from this survey?", "cursor-pointer bg-white block w-full px-4 py-2 text-sm text-left text-gray-700 hover:bg-gray-50") %>
              <% end %>
              <% if policy(@survey).delete_attempts? %>
                <%= confirm_button(survey_delete_attempts_path(@survey), "Delete All Attempts", "Are you sure you want to delete all attempts for this survey?", "cursor-pointer bg-white block w-full px-4 py-2 text-sm text-left text-gray-700 hover:bg-gray-50") %>
              <% end %>
              <% if policy(@survey).edit? %>
                <%= link_to "Edit", edit_survey_path(@survey), class: " cursor-pointer bg-white block w-full px-4 py-2 text-sm text-left text-gray-700 hover:bg-gray-50" %>
              <% end %>
              <% if policy(@survey).archive_survey? %>
                <%= confirm_button(archive_survey_path(@survey), "Archive", "Are you sure you want to archive this survey?", "cursor-pointer bg-white block w-full px-4 py-2 text-sm text-left text-gray-700 hover:bg-gray-50") %>
              <% end %>
              <% if policy(@survey).unarchive_survey? %>
                <%= confirm_button(unarchive_survey_path(@survey), "Unarchive", "Are you sure you want to activate this survey?", "cursor-pointer bg-white block w-full px-4 py-2 text-sm text-left text-gray-700 hover:bg-gray-50") %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>