config/routes.rb
Rails.application.routes.draw do

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: { invitations: "invitations", registrations: "registrations" }
  post "/register", to: "registrations#create"

  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root :to => "dashboard#index"
  get "/", to: "dashboard#index"

  resources :surveys do
    get "/attempts", to: "surveys#attempts", as: "attempts"
    resources :questions
    get "/pdf/checklist/:id", to: "survey/reports#checklist", as: "checklist_pdf"
    get "/pdf/score/:id", to: "survey/reports#score", as: "score_pdf"
    get "/pdf/yes_no/:id", to: "survey/reports#yes_no", as: "yes_no_pdf"
    get "/reports/checklist/:id", to: "survey/reports#checklist", as: "checklist_report"
    get "/reports/yes_no/:id", to: "survey/reports#yes_no", as: "yes_no_report"
    get "/reports/score/:id", to: "survey/reports#score", as: "score_report"
    patch "/attempts/:id/attempt", to: "attempts#submit", as: "submit_attempt"
    patch "/attempts/:id/submit", to: "submit#submit", as: "submit_report"
    get "/submit/checklist/:id", to: "submit#checklist", as: "checklist_submit"
    get "/submit/score/:id", to: "submit#score", as: "score_submit"
    get "/submit/yes_no/:id", to: "submit#yes_no", as: "yes_no_submit"
    get "delete_attempts", to: "surveys#delete_attempts", as: "delete_attempts"
  end

  get "/dashboard", to: "dashboard#index", as: "dashboard"
  get "/questions/reorder", to: "questions#reorder", as: "reorder_questions"
  get :activities, controller: :dashboard
  get "resend_invitation/:id", to: "users#resend_invitation", as: "resend_invitation_user"

  resources :users do
    get "/attempts", to: "user/attempts#index", as: "attempts"
    get "/surveys", to: "user/surveys#index", as: "surveys"
    get "/spaces", to: "user/spaces#index", as: "spaces"
    get "delete_attempts", to: "user/attempts#delete_attempts", as: "delete_attempts"
  end

  get "/surveys/:id/attempts/new", to: "attempts#new", as: "new_attempt"
  get "/surveys/:id/clone", to: "surveys#clone", as: "clone_survey"
  get "/surveys/:id/pin", to: "surveys#pin", as: "pin_survey"
  get "/surveys/:id/unpin", to: "surveys#unpin", as: "unpin_survey"
  get "/answer/:id", to: "attempts#answer", as: "answer_attempt"
  get "/score/:id", to: "attempts#score", as: "score_attempt"
  get "/check/:id", to: "attempts#check", as: "check_attempt"

  post "/change_folder/:id", to: "space/folders#change_folder", as: "change_folder"

  post "/surveys/:id/attempts/new", to: "attempts#create"
  get "/attempts", to: "attempts#index", as: "attempts"
  get "/attempts/:id", to: "attempts#show", as: "new_survey_attempt"

  scope "archive" do
    get "/surveys", to: "surveys#archived", as: "archived_surveys"
    get "/survey/:id", to: "surveys#archive_survey", as: "archive_survey"
    get "/survey/:id/restore", to: "surveys#unarchive_survey", as: "unarchive_survey"
    get "/users", to: "users#deactivated", as: "deactivated_users"
    get "/users/:id", to: "users#deactivate_user", as: "deactivate_user"
    get "/users/:id/restore", to: "users#activate_user", as: "activate_user"
  end

  get "/search/surveys", to: "search#surveys"
  get "/search/spaces-surveys-and-folders", to: "search#spaces_surveys_and_folders"
  get "/search/archived_surveys", to: "search#archived_surveys"
  get "/search/archived_users", to: "search#archived_users"
  scope "/settings" do
    get "/profile", to: "user#profile", as: "profile"
    get "/password", to: "user#password", as: "setting_password"
    patch "/password", to: "user#update_password", as: "change_password"
    patch "/profile", to: "user#update_profile", as: "update_profile"
    get "/preferences", to: "user#preferences", as: "user_preferences"
  end
  put ":id/permission", to: "user#update_permission", as: "set_permission"
  resources :spaces do
    resources :folders, module: "space" do
      collection do
        get "folders"
      end
    end
  end

  scope "/spaces" do
    get ":id/pin", to: "spaces#pin", as: "space_pin"
    get ":id/unpin", to: "spaces#unpin", as: "space_unpin"
    get ":id/archive", to: "spaces#archive", as: "space_archive"
    get ":id/unarchive", to: "spaces#unarchive", as: "space_unarchive"
  end
end

app/models/survey/participant.rb
class Survey::Participant < ActiveRecord::Base
  self.table_name = "survey_participant"
end

app/controllers/questions_controller.rb
class QuestionsController < BaseController
  before_action :set_survey, only: [:create, :destroy, :update, :edit, :new]
  before_action :set_question, only: [:edit, :update, :destroy, :show]

  def edit
    authorize @question
  end

  def destroy
    authorize @question
    @question.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@question) }
    end
  end

  def update
    authorize @question
    respond_to do |format|
      if @question.update(question_params)
        format.turbo_stream { render turbo_stream: turbo_stream.update(:questions, partial: "surveys/questions/questions", locals: { questions: @survey.questions.order(:order), survey: @survey }, formats: [:turbo_stream]) }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@question, partial: "questions/form", locals: { survey: @survey, question: @question }) }
      end
    end
  end

  def reorder
    authorize :question
    @question = Survey::Question.find(params[:question_id])
    @survey = Survey::Survey.find(params[:survey_id])
    @question.update(order: params[:order].to_i)

    if @question.save
      @change_order = @survey.questions.where.not(id: @question.id).order(:order)
      @change_order.size > 0 ?
        @change_order.each do |question|
        question.order < params[:order].to_i && question.order > 0 ? question.update(order: question.order - 1) :
          question.update(order: question.order + 1)
      end : nil

      partial = render_to_string(partial: "surveys/questions/questions", locals: { questions: @survey.questions.order(:order), survey: @survey })
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.update(:survey_questions, partial)
        end
        format.html
      end
    end
  end

  def create
    authorize :question
    @question = Survey::Question.new(question_params)
    @question.survey = @survey
    @question.order = @survey.questions.size + 1
    @question.save

    respond_to do |format|
      if @question.persisted?
        add_options(@question, @survey)
        format.turbo_stream {
          render turbo_stream: turbo_stream.update(:questions, partial: "surveys/questions/questions", locals: { questions: @survey.questions.order(:order), survey: @survey }, formats: [:turbo_stream]) +
                               turbo_stream.replace(Survey::Question.new, partial: "surveys/questions/form", locals: { survey: @survey, question: Survey::Question.new, message: "Question was added successfully." })
        }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(Survey::Question.new, partial: "surveys/questions/form", locals: { survey: @survey, question: @question }) }
      end
    end
  end

  private

  def add_options(question, survey)
    if survey.survey_type == "checklist"
      Survey::Option.new(text: "Yes", question: question, correct: true, weight: 1).save
    elsif survey.survey_type == "score"
      Survey::Option.new(text: "Score", question: question, correct: true, weight: 10).save
    else survey.survey_type == "yes_no"
      Survey::Option.new(text: "Yes", question: question, correct: true, weight: 1).save
      Survey::Option.new(text: "No", question: question, correct: false, weight: 0).save     end
  end

  def set_question
    @question = Survey::Question.find(params[:id])
  end

  def question_params
    params.require(:survey_question).permit(:text, :description, :survey_id)
  end

  def set_survey
    @survey = Survey::Survey.find(params[:survey_id])
  end
end

app/controllers/survey/base_controller.rb
class Survey::BaseController < BaseController
  include Pagy::Backend

  before_action :set_survey, only: [:create, :destroy, :update, :edit, :new]

  def set_survey
    @survey = Survey::Survey.find(params[:survey_id])
  end
end

app/controllers/survey/questions_controller.rb
class Survey::QuestionsController < Survey::BaseController
  before_action :set_question, only: [:edit, :update, :destroy, :show]

  def edit
    authorize [:survey, @question]
  end

  def destroy
    authorize [:survey, @question]
    @question.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@question) }
    end
  end

  def update
    authorize [:survey, @question]
    @question.update(question_params)
    redirect_to survey_path(@survey), notice: "Question was updated"
  end

  def reorder
    authorize [:survey, :question]
    @question = Survey::Question.find(params[:question_id])
    @survey = Survey::Survey.find(params[:survey_id])
    @question.update(order: params[:order].to_i)

    if @question.save
      @change_order = @survey.questions.where.not(id: @question.id).order(:order)
      @change_order.size > 0 ?
        @change_order.each do |question|
        question.order < params[:order].to_i && question.order > 0 ? question.update(order: question.order - 1) :
          question.update(order: question.order + 1)
      end : nil

      partial = render_to_string(partial: "surveys/questions/question", locals: { questions: @survey.questions.order(:order), survey: @survey })
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.update(:survey_questions, partial)
        end
        format.html
      end
    end
  end

  def create
    authorize [:survey, :question]
    @question = Survey::Question.new(question_params)
    @question.survey = @survey
    @question.order = @survey.questions.size + 1
    @question.save

    add_options(@question, @survey)

    respond_to do |format|
      if @question.persisted?
        format.turbo_stream {
          render turbo_stream: turbo_stream.update(:questions, partial: "surveys/questions/question", locals: { questions: @survey.questions.order(:order), survey: @survey }, formats: [:turbo_stream]) +
                               turbo_stream.replace(Survey::Question.new, partial: "surveys/questions/form", locals: { survey: @survey, question: Survey::Question.new, message: "Question was added successfully." })
        }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(Survey::Question.new, partial: "surveys/questions/form", locals: { survey: @survey, question: @question }) }
      end
    end
  end

  private

  def add_options(question, survey)
    if survey.survey_type == 0 #checklist
      Survey::Option.new(text: "Yes", question: question, correct: true, weight: 1).save
      Survey::Option.new(text: "No", question: question, correct: false, weight: 0).save
    else
      Survey::Option.new(text: "Score", question: question, correct: true, weight: 10).save
    end
  end

  def set_question
    @question = Survey::Question.find(params[:id])
  end

  def question_params
    params.require(:survey_question).permit(:text, :description, :survey_id)
  end
end

app/controllers/survey/reports_controller.rb
class Survey::ReportsController < Survey::BaseController
  before_action :set_attempt, only: [:checklist, :score, :submit, :yes_no]

  def checklist
    authorize [:survey, :report]
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "#{@attempt.participant.name}_#{@attempt.survey.name}",
               template: "pdf/checklist",
               layout: "pdf",
               formats: [:html]
      end
    end
  end

  def score
    authorize [:survey, :report]
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "#{@attempt.participant.name}_#{@attempt.survey.name}",
               template: "pdf/score",
               layout: "pdf",
               formats: [:html]
      end
    end
  end

  def yes_no
    authorize [:survey, :report]
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "#{@attempt.participant.name}_#{@attempt.survey.name}",
               template: "pdf/yes_no",
               layout: "pdf",
               formats: [:html]
      end
    end
  end

  private

  def attempt_params
    params.permit(:id, :comment)
  end

  def set_attempt
    @attempt ||= Survey::Attempt.find(params[:id])
  end
end

app/controllers/surveys_controller.rb
class SurveysController < BaseController
  include Pagy::Backend

  before_action :set_survey, only: [:edit, :update, :destroy, :show, :clone, :archive_survey, :unarchive_survey, :pin, :unpin]
  before_action :find_survey, only: [:attempts, :delete_attempts]

  def index
    authorize :Survey
    @title = "Home"
    surveys = Survey::Survey.all.active.where(folder_id: nil)
    @pagy, @surveys = pagy_nil_safe(params, surveys, items: LIMIT)
    render_partial("surveys/survey", collection: @surveys, cached: false) if stale?(@surveys)
  end

  def new
    authorize :Survey

    @survey = Survey::Survey.new
  end

  def edit
    authorize @survey
  end

  def destroy
    authorize @survey

    if DestroySurvey.call(@survey).result
      redirect_to archived_surveys_path, notice: "Survey was successfully deleted."
    end
  end

  def update
    authorize @survey
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to survey_path(@survey), notice: "Survey was successfully updated." }
      else
        format.html { redirect_to edit_survey_path(@survey), notice: "Failed to update survey." }
      end
    end
  end

  def create
    authorize :Survey
    @survey = Survey::Survey.new(survey_params)
    @survey.user = current_user

    respond_to do |format|
      if @survey.save
        if @survey.folder_id.present?
          @folder = Folder.find(@survey.folder_id)
          format.html { redirect_to space_folder_path(@folder.space, @folder), notice: "Survey was successfully created." }
        else
          format.html { redirect_to survey_path(@survey), notice: "Survey was successfully created." }
        end
      else
        format.html { redirect_to new_survey_path, notice: "Failed to create survey." }
      end
    end
  end

  def show
    authorize @survey
    @question = Survey::Question.new
    if RecentSurvey.where(user: current_user, survey_surveys: @survey).exists?
      RecentSurvey.where(user: current_user, survey_surveys: @survey).first.increment!(:count)
    else
      RecentSurvey.create(user: current_user, survey_surveys: @survey, count: 1)
    end
  end

  def attempts
    authorize @survey
    @survey = Survey::Survey.find(params[:survey_id])
    attempts = Survey::Attempt.where(survey_id: params[:survey_id]).includes(:participant, :survey, :actor).order(updated_at: :desc).order(created_at: :desc).all
    @pagy, @attempts = pagy(attempts, items: 10)
    render_partial("surveys/attempt", collection: @attempts, cached: true) if stale?(@attempts)
  end

  def delete_attempts
    authorize @survey
    Survey::Attempt.where(survey_id: params[:survey_id]).delete_all
    redirect_to survey_path(@survey), notice: "Survey attempts has been deleted successfully"
  end

  def pin
    authorize @survey
    @survey.update(pin: true)
    redirect_to survey_path(@survey), notice: "Survey has been pinned."
  end

  def unpin
    authorize @survey
    @survey.update(pin: false)
    redirect_to survey_path(@survey), notice: "Survey has been unpinned."
  end

  def clone
    authorize @survey

    @clone = Survey::Survey.new
    @clone.name = @survey.name + " (Copy)"
    @clone.survey_type = @survey.survey_type
    @clone.description = @survey.description.nil? ? "N/A" : @survey.description
    @clone.save

    @survey.questions.each do |question|
      cloned_question = Survey::Question.new(text: question.text, description: question.description, survey_id: @clone.id)
      cloned_question.save
      if cloned_question.persisted?
        add_options(cloned_question, @clone)
      end
    end

    redirect_to survey_path(@clone)
  end

  def archived
    authorize :survey

    surveys = Survey::Survey.inactive.order(archived_on: :asc)
    @pagy, @surveys = pagy_nil_safe(params, surveys, items: LIMIT)

    render_partial_as("surveys/archived_survey", collection: @surveys, as: :survey, cached: true) if stale?(@surveys)
  end

  def archive_survey
    authorize @survey
    if ArchiveSurvey.call(@survey).result
      redirect_to archived_surveys_path, notice: "Survey has been archived."
    end
  end

  def unarchive_survey
    authorize @survey
    @survey.update(active: true, archived_on: nil)
    redirect_to survey_path(@survey), notice: "Survey has been restored."
  end

  private

  def find_survey
    @survey = Survey::Survey.find(params[:survey_id])
  end

  def set_survey
    @survey = Survey::Survey.find(params[:id])
  end

  def survey_params
    params.require(:survey_survey).permit(:name, :survey_type, :description, :folder_id)
  end
end

app/controllers/user/surveys_controller.rb
class User::SurveysController < User::BaseController
  def index
    authorize [@user, :survey]
    surveys = Survey::Survey.active.where(user_id: @user.id).order(created_at: :desc)
    @pagy, @surveys = pagy_nil_safe(params, surveys, items: LIMIT)
    render_partial("user/surveys/survey", collection: @surveys) if stale?(@surveys)
  end
end

app/views/surveys/questions/_form.html.erb
<%= form_with(model: question, id: dom_id(question), url: survey_questions_path(@survey)) do |form| %>
  <main class="max-w-lg px-4 pt-6 pb-12 mx-auto space-y-6 lg:pb-16">
    <%= render "shared/form_messages", resource: question, message: local_assigns[:message] %>
    <%= render "shared/form_header", title: "Add New Question", subtitle: "Please fill in detail of new question" %>
    <div>
      <label for="filename" class="block text-sm font-medium text-gray-700">
        Question Text
      </label>
      <%= form.text_area :text, class: "mt-1 h-20 shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" %>
    </div>
    <div>
      <label for="comments" class="block text-sm font-medium text-gray-700">
        Question Description (optional)
      </label>
      <%= form.text_area :description, class: "h-24 mt-1 shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md", autocomplete: "off" %>
    </div>
    <div class="flex justify-end mt-6">
      <%= form.submit "Add Question ", class: "cursor-pointer ml-3  inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
    </div>
  </main>
<% end %>

app/views/surveys/questions/_question.turbo_stream.erb
     <ol class="space-y-6 pl-1 drag-zone" id="questions" 
    data-target="drag-item.sortContainer" data-action="drop->drag-item#drop">
    <% questions.each_with_index do |question, index| %>
<%= turbo_frame_tag dom_id(question) do %>

<li class="py-4 flex border-b border-gray-200" data-question-id="<%= question.id %>" data-index="<%= index + 1 %>"
data-survey-id="<%= survey.id %>" id= "<%= dom_id(question) %>"
data-action="dragstart->drag-item#dragstart
                      dragleave->drag-item#dragleave
                      dragover->drag-item#dragover
                      drag->drag-item#drag"
         draggable='true'>
  <div class="ml-3 w-full">
    <p class="text-sm font-medium text-gray-900"><%= question.text.upcase_first %></p>
    <p class="text-sm text-gray-500"><%= question.description %></p>
  </div>
  <div class="flex alight-right">
    <div class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
      <%= link_to "Edit", edit_survey_question_path(survey, question), class: "text-indigo-600", onmouseover: "this.style.color='#312e81'", onmouseout: "this.style.color='#4f46e5'" %>
      <%= link_to "Delete", survey_question_path(survey, question), class: "ml-4", data: {
                                                                      controller: "confirmation",
                                                                      "turbo-method": :delete,
                                                                      "confirmation-message-value": "Are you sure you want to delete this?",
                                                                      action: "confirmation#confirm",
                                                                    }, style: "color:#dc2626", onmouseover: "this.style.color='#7f1d1d'", onmouseout: "this.style.color='#dc2626'" %>
    </div>
  </div>
</li>
<% end %>
<% end %>
 </ol>

app/views/surveys/questions/_questions.turbo_stream.erb
     
<ol class="space-y-6 pl-1 drag-zone  px-6 ml-3" id="questions" 
    data-target="drag-item.sortContainer" data-action="drop->drag-item#drop">
  <% questions.each_with_index do |question, index| %>
    <%= turbo_frame_tag dom_id(question) do %>
      <% if policy(question.survey).update? %>
        <li class="py-4 flex border-b border-gray-200   " data-question-id="<%= question.id %>" data-index="<%= index + 1 %>"
data-survey-id="<%= survey.id %>" id= "<%= dom_id(question) %>"
data-action="dragstart->drag-item#dragstart
          dragleave->drag-item#dragleave
          dragover->drag-item#dragover
          drag->drag-item#drag"
          draggable="true">
          <p class="  drag">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
          </p>
          <div class="ml-4 w-full">
            <p class="text-sm font-medium text-gray-900"><%= question.text.upcase_first %></p>
            <p class="text-sm text-gray-500"><%= question.description %></p>
          </div>
          <div class="flex align-right ">
            <div class="whitespace-nowrap text-right text-sm font-medium">
              <% if policy(question.survey).edit? %>
                <%= link_to "Edit", edit_survey_question_path(survey, question), class: "text-indigo-600", onmouseover: "this.style.color='#312e81'", onmouseout: "this.style.color='#4f46e5'" %>
              <% end %>
              <% if policy(question.survey).edit? %>
                <%= link_to "Delete", survey_question_path(survey, question), class: "ml-4", data: {
                                                                                controller: "confirmation",
                                                                                "turbo-method": :delete,
                                                                                "confirmation-message-value": "Are you sure you want to delete this?",
                                                                                action: "confirmation#confirm",
                                                                              }, style: "color:#dc2626", onmouseover: "this.style.color='#7f1d1d'", onmouseout: "this.style.color='#dc2626'" %>
              <% end %>
            </div>
          </div>
        </li>
      <% else %>
        <li class="py-4 flex border-b border-gray-200" id= "<%= dom_id(question) %>" >
          <div class="ml-3 w-full">
            <p class="text-sm font-medium text-gray-900"><%= question.text.upcase_first %></p>
            <p class="text-sm text-gray-500"><%= question.description %></p>
          </div>
          <div class="flex align-right ">
            <div class="px-6 whitespace-nowrap text-right text-sm font-medium">
              <% if policy(question.survey).edit? %>
                <%= link_to "Edit", edit_survey_question_path(survey, question), class: "text-indigo-600", onmouseover: "this.style.color='#312e81'", onmouseout: "this.style.color='#4f46e5'" %>
              <% end %>
              <% if policy(question.survey).edit? %>
                <%= link_to "Delete", survey_question_path(survey, question), class: "ml-4", data: {
                                                                                controller: "confirmation",
                                                                                "turbo-method": :delete,
                                                                                "confirmation-message-value": "Are you sure you want to delete this?",
                                                                                action: "confirmation#confirm",
                                                                              }, style: "color:#dc2626", onmouseover: "this.style.color='#7f1d1d'", onmouseout: "this.style.color='#dc2626'" %>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>
    <% end %>
  <% end %>
</ol>